Update workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,5 +1,14 @@
 name: build
-on: [push, pull_request]
+on:
+  workflow_dispatch:
+  push:
+    branches:
+      - main
+    tags:
+      - '*'
+  pull_request:
+    branches:
+      - main
 jobs:
   setup:
     runs-on: ubuntu-latest
@@ -24,47 +33,64 @@ jobs:
           target: development
           load: true
           tags: itemtree-client-testing:latest
-      - 
+      -
         name: Run tests
         uses: addnab/docker-run-action@v1
         with:
           image: itemtree-client-testing:latest
-          shell: sh 
+          shell: sh
           run: sh /app/run_tests_ci ${{ github.sha }} ${{ secrets.CODECOV_TOKEN }}
       -
         name: Set up production Docker Buildx
-        id: production_builder
+        id: production_builder_test
         uses: docker/setup-buildx-action@v1
       -
-        name: Build and push production container
-        id: docker_build
+        name: Build production container # This is to know that the production build works
+        id: docker_build_test
         uses: docker/build-push-action@v2
         with:
           push: false
-          builder: ${{ steps.production_builder.outputs.name }}
+          builder: ${{ steps.production_builder_test.outputs.name }}
           target: production
           tags: namelivia/itemtree-client:latest
   deploy:
     runs-on: ubuntu-latest
     needs: setup
-    if: github.ref == 'refs/heads/main'
+    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
     steps:
-      -
-        name: Set up production Docker Buildx
-        id: production_builder
-        uses: docker/setup-buildx-action@v1
-      -
-        name: Login to DockerHub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      -
-        name: Build and push production container
-        id: docker_build
-        uses: docker/build-push-action@v2
-        with:
-          push: true
-          builder: ${{ steps.production_builder.outputs.name }}
-          target: production
-          tags: namelivia/itemtree-client:latest
+    -
+      name: Set up production Docker Buildx
+      id: production_builder
+      uses: docker/setup-buildx-action@v1
+    -
+      name: Login to DockerHub
+      uses: docker/login-action@v1
+      with:
+        username: ${{ secrets.DOCKERHUB_USERNAME }}
+        password: ${{ secrets.DOCKERHUB_TOKEN }}
+    -
+      name: Determine Docker tag
+      id: docker_tag
+      run: |
+        REF="${{ github.ref }}"
+        # Check if it's a push to the 'main' branch
+        if [[ "$REF" == "refs/heads/main" ]]; then
+          echo "TAG=latest" >> $GITHUB_ENV
+        # Check if it's a push of a tag
+        elif [[ "$REF" =~ ^refs/tags/ ]]; then
+          TAG_NAME="${REF#refs/tags/}" # Removes 'refs/tags/' prefix
+          echo "TAG=$TAG_NAME" >> $GITHUB_ENV
+        else
+          echo "Error: Unhandled Git reference type: $REF"
+          exit 1
+        fi
+        echo "Determined Docker TAG: ${{ env.TAG }}"
+    -
+      name: Build and push production container
+      uses: docker/build-push-action@v2
+      with:
+        push: true
+        builder: ${{ steps.production_builder.outputs.name }}
+        target: production
+        tags: namelivia/itemtree-client:${{ env.TAG }}
+
